//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int BranchId { get; set; }
        public string Address { get; set; }
        public int Latitude { get; set; }
        public int LatitudeMinutes { get; set; }
        public bool IsNorth { get; set; }
        public int Longitude { get; set; }
        public int LongitudeMinutes { get; set; }
        public bool IsEast { get; set; }
        public string BranchName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
    }
}
