//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalOrder
    {
        public int RentalOrderId { get; set; }
        public System.DateTime RentStartDate { get; set; }
        public System.DateTime RentEndDate { get; set; }
        public Nullable<System.DateTime> ActualRentEndDate { get; set; }
        public int UserId { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
